### ISSUE TITLE
Combox cho chọn trang chủ bị mờ

### ISSUE THREAD

**Issue by tuanan94** [oPhuongXuongQuang/ghinhap#23]
Đây có phải bug ko nhỉ?

Bị mờ khi chưa chọn gì hết
Ngoải ra nếu chọn rồi muốn quay lại default. Thì chỗ default ko có text nào hết

**Comment by oPhuongXuongQuang** [comment]
Chụp hình chỗ mờ đi!

Còn về text để là Default, ban đầu cũng có nghĩ rồi, nhưng sợ trùng với tên note...

**Comment by tuanan94** [comment]
Hình chổ bị mờ: 
![img_0195](https://cloud.githubusercontent.com/assets/9337622/9526603/81434e22-4d14-11e5-90e1-90a2326e7e70.jpg)

**Comment by oPhuongXuongQuang** [comment]
Chỗ chữ trên combox box là placeholder nên có màu xám. Nếu chưa chọn gì thì set là placeholder.

**Comment by tuanan94** [comment]
Nhìn có vẻ như ko thể chọn được. M nghĩ có nên làm cho nó nỗi lên như thằng kia ko

**Comment by oPhuongXuongQuang** [comment]
Cũng được nhưng chắc ko có vấn đề vì có hint rồi.

**Comment by tuanan94** [comment]
ok. Vay close
