### ISSUE TITLE
Bug tái hiện khi mạng chậm

### ISSUE THREAD

**Issue by tuanan94** [oPhuongXuongQuang/ghinhap#24]
Step:
1.Tạo 2 note.
2.Modify note trên, đợi cho lưu lại
3.Bấm hình sọt rác.
4. Ngắt mạng
5. Bấm xoá.
6. Hiện tượng: note dưới mang nội dung của note thứ 2. Cho dù có bấm refresh đi nữa cũng ko có tác dụng
Expect: hiện content của note 2, hoặc báo lỗi mạng. Có gì thảo luận lại solution

**Comment by oPhuongXuongQuang** [comment]
Ok. Lỗi này sẽ sửa cho hiện content của note 2, để đảm bảo offline vẫn sử dụng dc app.

**Comment by tuanan94** [comment]
Nhưng lúc đó có content của note 2 lưu dưới local chưa?
Vì không thể request để lấy được (no connection )
